---
- hosts: BCF-Controller
  connection: local
  gather_facts: no
  tasks:
    - name: Create/Delete tenant
      bcf_tenant:
          controller: '{{ inventory_hostname }}'
          name: auto_tenant1
          state: present

