---
- hosts: 10.8.23.15
  connection: local
  gather_facts: no
  tasks:
    - name: Create/Delete tenant
      bcf_tenant:
          controller: '{{ inventory_hostname }}'
          name: auto_tenant1
          state: present
          validate_certs: false
          access_token: 'FJze_a9Ho6LDrvFOAWpO3UXuTs0rfR7M'
