---
- hosts: BCF-Controller
  connection: local
  gather_facts: no
  tasks:
    - name: Create/Delete tenant
      bcf_tenant:
          controller: '{{ inventory_hostname }}'
          name: auto_tenant1
          state: present

    - name: Create/Delete segment
      bcf_segment:
          controller: '{{ inventory_hostname }}'
          tenantName: auto_tenant1
          segmentName: auto_segment1
          tenantState: present
          segmentState: present

    - name: Create/Delete logical router
      bcf_logicalrouter:
          controller: '{{ inventory_hostname }}'
          tenantName: auto_tenant1
          segmentName: auto_segment1
          ipcidr: '1.1.1.1/24'
          segIntState: present

